import { defineSwarm } from './runtime.ts';

export const planImplementReviewSwarm = defineSwarm({
  id: 'plan-implement-review',
  title: 'Planner / Implementer Hub',
  summary:
    'A hub-and-spoke swarm where the planner owns user conversation, prompt proposal, and review, while worker agents execute implementation and artifact-writing tasks.',
  agents: [
    {
      id: 'planner',
      title: 'Planner',
      summary: 'Hub agent that talks to the user, proposes prompts, opens gates, and later reviews work.',
      kind: 'hub',
      owned_state_ids: ['planning_conversation', 'first_prompt_approval', 'auto_review', 'artifact_forking', 'step_approval'],
      session_kinds: ['planning_conversation'],
      role_prompt:
        'You are the planner/reviewer hub for a workflow runtime with explicit user gates.',
      operating_guidelines: [
        'Drive the conversation toward a tightly scoped implementer step before opening a gate.',
        'Do not emit workflow markers until the current prompt candidate is ready for approval.',
        'When the prompt candidate is ready, present exactly one explicit artifact for the user gate.',
        'Refer to repo-root relative paths or the authoritative runtime workspace path only; do not direct workers to the source repository checkout.',
      ],
      review_role_prompt:
        'You are the planner/reviewer hub evaluating implementer output for a hub-and-spoke swarm run.',
      review_guidelines: [
        'Base the review on the approved prompt candidate, the implementer output, and the observed result.',
        'Ground any repo inspection in the authoritative implementer workspace, not the original source repository checkout.',
        'If the implementer faithfully completed the approved prompt without a material problem, emit the accepted marker.',
        'Emit fixup_required only when you can provide an implementer-ready fixup prompt.',
        'Emit replan_required only when renewed user planning is necessary before more worker execution.',
      ],
      expected_marker_ids: [
        'first_prompt_candidate',
        'review_accepted',
        'review_fixup_required',
        'review_replan_required',
      ],
      target_artifact_kind_ids: ['prompt_candidate'],
      target_gate_rule_ids: ['prompt_candidate_approval', 'step_packet_approval'],
    },
    {
      id: 'implementer',
      title: 'Implementer',
      summary: 'Worker agent that executes approved prompts inside a workspace.',
      kind: 'worker',
      owned_state_ids: ['implementing', 'fixup_implementing'],
      session_kinds: ['implementing'],
      role_prompt:
        'You are the implementer worker for a hub-and-spoke swarm run. Execute the approved task directly in the workspace.',
      operating_guidelines: [
        'Treat the approved prompt candidate as the concrete task to execute.',
        'Treat the runtime-supplied workspace path as authoritative and do not edit the source repository checkout.',
        'Make code changes in the workspace, verify the slice honestly, and leave a readable session trail.',
        'Do not re-plan the task unless the approved prompt is impossible to execute as written.',
      ],
      review_role_prompt: null,
      review_guidelines: [],
      expected_marker_ids: [],
      target_artifact_kind_ids: [],
      target_gate_rule_ids: [],
    },
    {
      id: 'tutorial_writer',
      title: 'Tutorial Writer',
      summary: 'Worker agent that turns an accepted implementation step into a user-facing tutorial artifact.',
      kind: 'worker',
      owned_state_ids: ['artifact_forking'],
      session_kinds: ['tutorial_writing'],
      role_prompt:
        'You are the tutorial writer worker for a hub-and-spoke swarm run. Produce a concise user-facing tutorial artifact from the accepted step.',
      operating_guidelines: [
        'Base the tutorial on the approved prompt, the implementer result, and the accepted review context.',
        'If you inspect files, use the authoritative implementer workspace path from runtime context rather than the source repository checkout.',
        'Explain what changed, why it matters, and what the user should understand before approving the next step.',
        'Emit exactly one explicit tutorial artifact marker and no other workflow markers.',
      ],
      review_role_prompt: null,
      review_guidelines: [],
      expected_marker_ids: ['tutorial_artifact'],
      target_artifact_kind_ids: ['tutorial_artifact'],
      target_gate_rule_ids: ['step_packet_approval'],
    },
    {
      id: 'next_prompt_writer',
      title: 'Next Prompt Writer',
      summary: 'Worker agent that proposes the next implementer prompt after an accepted step.',
      kind: 'worker',
      owned_state_ids: ['artifact_forking'],
      session_kinds: ['next_prompt_writing'],
      role_prompt:
        'You are the next-prompt writer worker for a hub-and-spoke swarm run. Produce the next bounded implementer prompt from the accepted step.',
      operating_guidelines: [
        'Base the next prompt on the workflow goal, the accepted step, and the current repository direction.',
        'If you inspect files, use the authoritative implementer workspace path from runtime context rather than the source repository checkout.',
        'Keep the prompt implementer-ready, scoped, and explicit enough to send to a worker without more planning.',
        'Emit exactly one explicit next-prompt artifact marker and no other workflow markers.',
      ],
      review_role_prompt: null,
      review_guidelines: [],
      expected_marker_ids: ['next_prompt_artifact'],
      target_artifact_kind_ids: ['next_prompt_artifact'],
      target_gate_rule_ids: ['step_packet_approval'],
    },
  ],
  allowed_routes: [
    {
      id: 'planner_to_implementer',
      from_agent_id: 'planner',
      to_agent_id: 'implementer',
      title: 'Planner delegates implementation',
      summary: 'The planner can send an approved prompt candidate to the implementer.',
    },
    {
      id: 'planner_to_tutorial_writer',
      from_agent_id: 'planner',
      to_agent_id: 'tutorial_writer',
      title: 'Planner delegates tutorial writing',
      summary: 'After an accepted review, the planner can fork a bounded tutorial-writing worker.',
    },
    {
      id: 'planner_to_next_prompt_writer',
      from_agent_id: 'planner',
      to_agent_id: 'next_prompt_writer',
      title: 'Planner delegates next prompt writing',
      summary: 'After an accepted review, the planner can fork a bounded next-prompt worker.',
    },
  ],
  gate_rules: [
    {
      id: 'prompt_candidate_approval',
      title: 'Prompt Candidate Approval',
      summary: 'Open a user gate when the planner emits the first prompt candidate.',
      owner_agent_id: 'planner',
      workflow_gate_ids: ['first_prompt_gate'],
      artifact_kind_id: 'prompt_candidate',
      unlocks_route_id: 'planner_to_implementer',
    },
    {
      id: 'step_packet_approval',
      title: 'Step Packet Approval',
      summary: 'Open a user gate when tutorial and next-prompt artifacts are both ready.',
      owner_agent_id: 'planner',
      workflow_gate_ids: ['step_approval_gate'],
      artifact_kind_id: 'next_prompt_artifact',
      unlocks_route_id: 'planner_to_implementer',
    },
  ],
  artifact_kinds: [
    {
      id: 'prompt_candidate',
      title: 'Prompt Candidate',
      summary: 'The implementer-ready prompt proposed by the planner and shown at the approval gate.',
    },
    {
      id: 'tutorial_artifact',
      title: 'Tutorial Artifact',
      summary: 'The user-facing tutorial produced after an accepted implementation step.',
    },
    {
      id: 'next_prompt_artifact',
      title: 'Next Prompt Artifact',
      summary: 'The next implementer-ready prompt produced after an accepted implementation step.',
    },
  ],
});
